apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: kubernetes-todo
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: database-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: todo-backend:local
          imagePullPolicy: IfNotPresent
          command: ["/app/prestart.sh"]
          envFrom:
            - configMapRef:
                name: todo-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-database
                  key: POSTGRES_PASSWORD
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
